services:
  linux-desktop:
    build: .
    container_name: linux-desktop
    privileged: true
    # Changed from network_mode: host to explicit port mapping for Windows compatibility
    ports:
      - "6080:6080"  # noVNC web interface
      - "5901:5901"  # VNC port
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - apparmor:unconfined
    # Add shared memory size for Chrome
    shm_size: 2gb
    volumes:
      - ./shared:/home/eagle/shared  # mount host folder
      - ./new_cache:/home/eagle/.config/google-chrome  # mount cache folder
      - /tmp/.X11-unix:/tmp/.X11-unix  # clipboard/audio support
      - /dev:/dev  # access to network devices
    environment:
      - DISPLAY=:0
      - NO_AT_BRIDGE=1
      - PULSE_DISABLE_AUTOSPAWN=1
      - XDG_RUNTIME_DIR=/tmp
    restart: unless-stopped
