services:
  linux-desktop:
    build: .
    container_name: linux-desktop
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - apparmor:unconfined
    ports:
      - "6080:6080"  # browser access
      - "5901:5901"  # optional VNC client
    volumes:
      - ./shared:/home/eagle/shared  # mount host folder
      - /tmp/.X11-unix:/tmp/.X11-unix  # clipboard/audio support
      - /dev:/dev  # access to network devices
    environment:
      - PULSE_SERVER=unix:/tmp/pulse-native
      - DISPLAY=:0
    restart: unless-stopped
