services:
  linux-desktop:
    build: .
    container_name: linux-desktop
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - apparmor:unconfined
    # Note: ports are not needed with network_mode: host
    # The services will be available directly on host ports 6080 and 5901
    volumes:
      - ./shared:/home/eagle/shared  # mount host folder
      - /tmp/.X11-unix:/tmp/.X11-unix  # clipboard/audio support
      - /dev:/dev  # access to network devices
    environment:
      - DISPLAY=:0
      - NO_AT_BRIDGE=1
      - PULSE_DISABLE_AUTOSPAWN=1
      - XDG_RUNTIME_DIR=/tmp
    restart: unless-stopped
